apiVersion: apps/v1
kind: Deployment
metadata:
  name: msfirmeware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msfirmeware
  template:
    metadata:
      labels:
        app: msfirmeware
    spec:
      containers:
      - name: msfirmeware
        image: ghofrane694/msfirmeware:latest
        ports:
        - containerPort: 5005
