apiVersion: apps/v1
kind: Deployment
metadata:
  name: msclient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msclient
  template:
    metadata:
      labels:
        app: msclient
    spec:
      containers:
      - name: msclient
        image: ghofrane694/msclient:latest
        ports:
        - containerPort: 5001
