apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval:     10s
      evaluation_interval: 10s
    rule_files:
      - rules.yml
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      - job_name: alertmanager
        static_configs:
          - targets: ['alertmanager:9093']

      - job_name: client
        metrics_path: '/metrics'
        static_configs:
          - targets: ['host.docker.internal:5001']
