apiVersion: apps/v1
kind: Deployment
metadata:
  name: msauth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msauth
  template:
    metadata:
      labels:
        app: msauth
    spec:
      containers:
      - name: msauth
        image: ghofrane694/msauth:latest
        ports:
        - containerPort: 5000