apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-microservice
  template:
    metadata:
      labels:
        app: node-microservice
    spec:
      containers:
      - name: node-microservice
        image: ghofrab
        imagePullPolicy: Never
        ports:
        - containerPort: 3000